# generated by datamodel-codegen:
#   filename:  20260412_232012.json
#   timestamp: 2026-05-04T00:43:38+00:00

from __future__ import annotations

from pydantic import BaseModel


class Header(BaseModel):
    etag: None
    updated: str


class Item(BaseModel):
    title: str
    summary: str
    published: str
    guid: str
    link: str


class Model(BaseModel):
    header: Header
    items: list[Item]
